application: glazbaapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /vk
  static_files: vk.html
  upload: vk.html

- url: /
  static_files: index.html
  upload: index.html

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /font
  static_dir: font

- url: /less
  static_dir: less

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

libraries:
- name: django
  version: "1.2"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^.git(.*)$
- ^(.*/)?.*\.psd$